Spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: ${DDL}
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

datainit: ${DATAINIT}
userinit: ${USERINIT}

username: ${USERNAME}
password: ${PASSWORD}